export const CONSTELLATIONS = [
  { id: "andromeda", name: "Andromeda", nameEs: "Andromeda", iau: "And", raHours: 0.8, decDeg: 38 },
  { id: "antlia", name: "Antlia", nameEs: "Bomba de Aire", iau: "Ant", raHours: 10.4, decDeg: -32 },
  { id: "apus", name: "Apus", nameEs: "Ave del Paraiso", iau: "Aps", raHours: 16.0, decDeg: -75 },
  { id: "aquarius", name: "Aquarius", nameEs: "Acuario", iau: "Aqr", raHours: 22.3, decDeg: -10 },
  { id: "aquila", name: "Aquila", nameEs: "Aguila", iau: "Aql", raHours: 19.7, decDeg: 3 },
  { id: "ara", name: "Ara", nameEs: "Altar", iau: "Ara", raHours: 17.4, decDeg: -53 },
  { id: "aries", name: "Aries", nameEs: "Aries", iau: "Ari", raHours: 2.6, decDeg: 21 },
  { id: "auriga", name: "Auriga", nameEs: "Cochero", iau: "Aur", raHours: 5.95, decDeg: 42 },
  { id: "bootes", name: "Bootes", nameEs: "Boyero", iau: "Boo", raHours: 14.7, decDeg: 31, aliases: ["Boötes"] },
  { id: "caelum", name: "Caelum", nameEs: "Cincel", iau: "Cae", raHours: 4.7, decDeg: -39 },
  { id: "camelopardalis", name: "Camelopardalis", nameEs: "Jirafa", iau: "Cam", raHours: 6.0, decDeg: 70 },
  { id: "cancer", name: "Cancer", nameEs: "Cancer", iau: "Cnc", raHours: 8.7, decDeg: 20 },
  { id: "canes-venatici", name: "Canes Venatici", nameEs: "Perros de Caza", iau: "CVn", raHours: 13.0, decDeg: 40 },
  { id: "canis-major", name: "Canis Major", nameEs: "Can Mayor", iau: "CMa", raHours: 6.8, decDeg: -22 },
  { id: "canis-minor", name: "Canis Minor", nameEs: "Can Menor", iau: "CMi", raHours: 7.5, decDeg: 7 },
  { id: "capricornus", name: "Capricornus", nameEs: "Capricornio", iau: "Cap", raHours: 21.0, decDeg: -18 },
  { id: "carina", name: "Carina", nameEs: "Quilla", iau: "Car", raHours: 8.7, decDeg: -60 },
  { id: "cassiopeia", name: "Cassiopeia", nameEs: "Casiopea", iau: "Cas", raHours: 1.0, decDeg: 60 },
  { id: "centaurus", name: "Centaurus", nameEs: "Centauro", iau: "Cen", raHours: 13.0, decDeg: -47 },
  { id: "cepheus", name: "Cepheus", nameEs: "Cefeo", iau: "Cep", raHours: 22.0, decDeg: 70 },
  { id: "cetus", name: "Cetus", nameEs: "Ballena", iau: "Cet", raHours: 1.7, decDeg: -10 },
  { id: "chamaeleon", name: "Chamaeleon", nameEs: "Camaleon", iau: "Cha", raHours: 10.7, decDeg: -78 },
  { id: "circinus", name: "Circinus", nameEs: "Compas", iau: "Cir", raHours: 14.6, decDeg: -63 },
  { id: "columba", name: "Columba", nameEs: "Paloma", iau: "Col", raHours: 5.9, decDeg: -35 },
  { id: "coma-berenices", name: "Coma Berenices", nameEs: "Cabellera de Berenice", iau: "Com", raHours: 12.8, decDeg: 23 },
  { id: "corona-australis", name: "Corona Australis", nameEs: "Corona Austral", iau: "CrA", raHours: 19.0, decDeg: -40 },
  { id: "corona-borealis", name: "Corona Borealis", nameEs: "Corona Boreal", iau: "CrB", raHours: 15.8, decDeg: 31 },
  { id: "corvus", name: "Corvus", nameEs: "Cuervo", iau: "Crv", raHours: 12.4, decDeg: -18 },
  { id: "crater", name: "Crater", nameEs: "Copa", iau: "Crt", raHours: 11.4, decDeg: -15 },
  { id: "crux", name: "Crux", nameEs: "Cruz del Sur", iau: "Cru", raHours: 12.5, decDeg: -60 },
  { id: "cygnus", name: "Cygnus", nameEs: "Cisne", iau: "Cyg", raHours: 20.6, decDeg: 43 },
  { id: "delphinus", name: "Delphinus", nameEs: "Delfin", iau: "Del", raHours: 20.7, decDeg: 12 },
  { id: "dorado", name: "Dorado", nameEs: "Dorado", iau: "Dor", raHours: 5.0, decDeg: -60 },
  { id: "draco", name: "Draco", nameEs: "Dragon", iau: "Dra", raHours: 17.5, decDeg: 65 },
  { id: "equuleus", name: "Equuleus", nameEs: "Caballito", iau: "Equ", raHours: 21.2, decDeg: 7 },
  { id: "eridanus", name: "Eridanus", nameEs: "Eridano", iau: "Eri", raHours: 3.8, decDeg: -22 },
  { id: "fornax", name: "Fornax", nameEs: "Horno", iau: "For", raHours: 3.0, decDeg: -30 },
  { id: "gemini", name: "Gemini", nameEs: "Geminis", iau: "Gem", raHours: 7.0, decDeg: 22 },
  { id: "grus", name: "Grus", nameEs: "Grulla", iau: "Gru", raHours: 22.5, decDeg: -45 },
  { id: "hercules", name: "Hercules", nameEs: "Hercules", iau: "Her", raHours: 17.0, decDeg: 30 },
  { id: "horologium", name: "Horologium", nameEs: "Reloj", iau: "Hor", raHours: 3.3, decDeg: -53 },
  { id: "hydra", name: "Hydra", nameEs: "Hidra", iau: "Hya", raHours: 10.7, decDeg: -20 },
  { id: "hydrus", name: "Hydrus", nameEs: "Hidra del Sur", iau: "Hyi", raHours: 2.5, decDeg: -70 },
  { id: "indus", name: "Indus", nameEs: "Indio", iau: "Ind", raHours: 21.2, decDeg: -55 },
  { id: "lacerta", name: "Lacerta", nameEs: "Lagarto", iau: "Lac", raHours: 22.5, decDeg: 46 },
  { id: "leo", name: "Leo", nameEs: "Leo", iau: "Leo", raHours: 10.7, decDeg: 15 },
  { id: "leo-minor", name: "Leo Minor", nameEs: "Leo Menor", iau: "LMi", raHours: 10.2, decDeg: 33 },
  { id: "lepus", name: "Lepus", nameEs: "Liebre", iau: "Lep", raHours: 5.5, decDeg: -20 },
  { id: "libra", name: "Libra", nameEs: "Libra", iau: "Lib", raHours: 15.2, decDeg: -15 },
  { id: "lupus", name: "Lupus", nameEs: "Lobo", iau: "Lup", raHours: 15.3, decDeg: -42 },
  { id: "lynx", name: "Lynx", nameEs: "Lince", iau: "Lyn", raHours: 7.8, decDeg: 45 },
  { id: "lyra", name: "Lyra", nameEs: "Lira", iau: "Lyr", raHours: 18.8, decDeg: 37 },
  { id: "mensa", name: "Mensa", nameEs: "Mesa", iau: "Men", raHours: 5.5, decDeg: -77 },
  { id: "microscopium", name: "Microscopium", nameEs: "Microscopio", iau: "Mic", raHours: 21.0, decDeg: -36 },
  { id: "monoceros", name: "Monoceros", nameEs: "Unicornio", iau: "Mon", raHours: 7.0, decDeg: -5 },
  { id: "musca", name: "Musca", nameEs: "Mosca", iau: "Mus", raHours: 12.6, decDeg: -70 },
  { id: "norma", name: "Norma", nameEs: "Escuadra", iau: "Nor", raHours: 16.0, decDeg: -51 },
  { id: "octans", name: "Octans", nameEs: "Octante", iau: "Oct", raHours: 21.0, decDeg: -85 },
  { id: "ophiuchus", name: "Ophiuchus", nameEs: "Ofiuco", iau: "Oph", raHours: 17.2, decDeg: -6 },
  { id: "orion", name: "Orion", nameEs: "Orion", iau: "Ori", raHours: 5.6, decDeg: 5 },
  { id: "pavo", name: "Pavo", nameEs: "Pavo", iau: "Pav", raHours: 19.5, decDeg: -65 },
  { id: "pegasus", name: "Pegasus", nameEs: "Pegaso", iau: "Peg", raHours: 22.7, decDeg: 20 },
  { id: "perseus", name: "Perseus", nameEs: "Perseo", iau: "Per", raHours: 3.4, decDeg: 45 },
  { id: "phoenix", name: "Phoenix", nameEs: "Fenix", iau: "Phe", raHours: 0.8, decDeg: -48 },
  { id: "pictor", name: "Pictor", nameEs: "Pintor", iau: "Pic", raHours: 5.7, decDeg: -52 },
  { id: "pisces", name: "Pisces", nameEs: "Piscis", iau: "Psc", raHours: 0.5, decDeg: 10 },
  { id: "piscis-austrinus", name: "Piscis Austrinus", nameEs: "Pez Austral", iau: "PsA", raHours: 22.5, decDeg: -30 },
  { id: "puppis", name: "Puppis", nameEs: "Popa", iau: "Pup", raHours: 7.8, decDeg: -30 },
  { id: "pyxis", name: "Pyxis", nameEs: "Brujula", iau: "Pyx", raHours: 8.9, decDeg: -27 },
  { id: "reticulum", name: "Reticulum", nameEs: "Reticulo", iau: "Ret", raHours: 3.9, decDeg: -60 },
  { id: "sagitta", name: "Sagitta", nameEs: "Flecha", iau: "Sge", raHours: 19.8, decDeg: 18 },
  { id: "sagittarius", name: "Sagittarius", nameEs: "Sagitario", iau: "Sgr", raHours: 19.0, decDeg: -25 },
  { id: "scorpius", name: "Scorpius", nameEs: "Escorpio", iau: "Sco", raHours: 16.5, decDeg: -30 },
  { id: "sculptor", name: "Sculptor", nameEs: "Escultor", iau: "Scl", raHours: 0.5, decDeg: -32 },
  { id: "scutum", name: "Scutum", nameEs: "Escudo", iau: "Sct", raHours: 18.7, decDeg: -10 },
  { id: "serpens", name: "Serpens", nameEs: "Serpiente", iau: "Ser", raHours: 16.8, decDeg: 6 },
  { id: "sextans", name: "Sextans", nameEs: "Sextante", iau: "Sex", raHours: 10.2, decDeg: -2 },
  { id: "taurus", name: "Taurus", nameEs: "Tauro", iau: "Tau", raHours: 4.6, decDeg: 16 },
  { id: "telescopium", name: "Telescopium", nameEs: "Telescopio", iau: "Tel", raHours: 19.0, decDeg: -52 },
  { id: "triangulum", name: "Triangulum", nameEs: "Triangulo", iau: "Tri", raHours: 2.0, decDeg: 32 },
  { id: "triangulum-australe", name: "Triangulum Australe", nameEs: "Triangulo Austral", iau: "TrA", raHours: 16.1, decDeg: -65 },
  { id: "tucana", name: "Tucana", nameEs: "Tucan", iau: "Tuc", raHours: 0.0, decDeg: -62 },
  { id: "ursa-major", name: "Ursa Major", nameEs: "Osa Mayor", iau: "UMa", raHours: 11.3, decDeg: 55 },
  { id: "ursa-minor", name: "Ursa Minor", nameEs: "Osa Menor", iau: "UMi", raHours: 15.0, decDeg: 75 },
  { id: "vela", name: "Vela", nameEs: "Vela", iau: "Vel", raHours: 9.5, decDeg: -45 },
  { id: "virgo", name: "Virgo", nameEs: "Virgo", iau: "Vir", raHours: 13.2, decDeg: -5 },
  { id: "volans", name: "Volans", nameEs: "Pez Volador", iau: "Vol", raHours: 8.0, decDeg: -70 },
  { id: "vulpecula", name: "Vulpecula", nameEs: "Zorra", iau: "Vul", raHours: 20.2, decDeg: 24 }
];
