export const NEBULA_LANDMARKS = [
  {
    id: "horsehead-nebula",
    name: "Horsehead Nebula",
    nameEs: "Nebulosa Cabeza de Caballo",
    catalog: ["Barnard 33", "B33", "IC 434"],
    constellation: "Orion",
    raHours: 5.683,
    decDeg: -2.45,
    objectType: "Nebulosa oscura",
    aliases: ["Horsehead", "Horse Head", "Cabeza de Caballo"],
    anchorStar: {
      id: "alnitak",
      name: "Alnitak",
      constellation: "Orion",
      raHours: 5.6793,
      decDeg: -1.9426,
      mag: 1.74,
      distanceLy: 1260,
      spectral: "O9.5Iab",
      bv: -0.2,
      searchAliases: ["Zeta Orionis", "Zeta Ori"]
    }
  },
  {
    id: "orion-nebula",
    name: "Orion Nebula",
    nameEs: "Nebulosa de Orion",
    catalog: ["M42", "NGC 1976"],
    constellation: "Orion",
    raHours: 5.588,
    decDeg: -5.391,
    objectType: "Nebulosa de emision",
    aliases: ["Great Orion Nebula"],
    anchorStar: {
      id: "theta1-orionis-c",
      name: "Theta1 Orionis C",
      constellation: "Orion",
      raHours: 5.5906,
      decDeg: -5.3897,
      mag: 5.13,
      distanceLy: 1344,
      spectral: "O7V",
      bv: -0.2,
      searchAliases: ["Theta 1 Ori C", "Trapezium C", "HD 37022"]
    }
  },
  {
    id: "flame-nebula",
    name: "Flame Nebula",
    nameEs: "Nebulosa de la Llama",
    catalog: ["NGC 2024", "Sh2-277"],
    constellation: "Orion",
    raHours: 5.690,
    decDeg: -1.85,
    objectType: "Nebulosa de emision",
    aliases: ["Flame"],
    anchorStar: {
      id: "alnitak",
      name: "Alnitak",
      constellation: "Orion",
      raHours: 5.6793,
      decDeg: -1.9426,
      mag: 1.74,
      distanceLy: 1260,
      spectral: "O9.5Iab",
      bv: -0.2,
      searchAliases: ["Zeta Orionis", "Zeta Ori"]
    }
  },
  {
    id: "running-man-nebula",
    name: "Running Man Nebula",
    nameEs: "Nebulosa del Corredor",
    catalog: ["NGC 1977"],
    constellation: "Orion",
    raHours: 5.590,
    decDeg: -4.85,
    objectType: "Nebulosa de reflexion",
    aliases: ["Running Man"],
    anchorStar: {
      id: "42-orionis",
      name: "42 Orionis",
      constellation: "Orion",
      raHours: 5.5897,
      decDeg: -4.838,
      mag: 4.59,
      distanceLy: 900,
      spectral: "B1V",
      bv: -0.15,
      searchAliases: ["c Orionis"]
    }
  },
  {
    id: "rosette-nebula",
    name: "Rosette Nebula",
    nameEs: "Nebulosa Roseta",
    catalog: ["NGC 2237", "Caldwell 49"],
    constellation: "Monoceros",
    raHours: 6.533,
    decDeg: 4.95,
    objectType: "Nebulosa de emision",
    aliases: ["Rosette"],
    anchorStar: {
      id: "hd-46223",
      name: "HD 46223",
      constellation: "Monoceros",
      raHours: 6.539,
      decDeg: 4.94,
      mag: 7.27,
      distanceLy: 5200,
      spectral: "O4V",
      bv: -0.18,
      searchAliases: ["NGC 2244"]
    }
  },
  {
    id: "carina-nebula",
    name: "Carina Nebula",
    nameEs: "Nebulosa de Carina",
    catalog: ["NGC 3372", "Caldwell 92"],
    constellation: "Carina",
    raHours: 10.752,
    decDeg: -59.867,
    objectType: "Nebulosa de emision",
    aliases: ["Eta Carinae Nebula"],
    anchorStar: {
      id: "eta-carinae",
      name: "Eta Carinae",
      constellation: "Carina",
      raHours: 10.751,
      decDeg: -59.685,
      mag: 4.3,
      distanceLy: 7500,
      spectral: "B",
      bv: 0.6,
      searchAliases: ["Eta Car", "HD 93308"]
    }
  },
  {
    id: "lagoon-nebula",
    name: "Lagoon Nebula",
    nameEs: "Nebulosa Laguna",
    catalog: ["M8", "NGC 6523"],
    constellation: "Sagittarius",
    raHours: 18.061,
    decDeg: -24.386,
    objectType: "Nebulosa de emision",
    aliases: ["Lagoon"],
    anchorStar: {
      id: "9-sagittarii",
      name: "9 Sagittarii",
      constellation: "Sagittarius",
      raHours: 18.0647,
      decDeg: -24.3607,
      mag: 5.97,
      distanceLy: 4100,
      spectral: "O4V",
      bv: -0.2,
      searchAliases: ["9 Sgr"]
    }
  },
  {
    id: "trifid-nebula",
    name: "Trifid Nebula",
    nameEs: "Nebulosa Trifida",
    catalog: ["M20", "NGC 6514"],
    constellation: "Sagittarius",
    raHours: 18.034,
    decDeg: -23.03,
    objectType: "Nebulosa mixta",
    aliases: ["Trifid"],
    anchorStar: {
      id: "hd-164492a",
      name: "HD 164492A",
      constellation: "Sagittarius",
      raHours: 18.034,
      decDeg: -22.971,
      mag: 7.6,
      distanceLy: 5200,
      spectral: "O7.5V",
      bv: -0.18,
      searchAliases: ["Trifid central star"]
    }
  },
  {
    id: "eagle-nebula",
    name: "Eagle Nebula",
    nameEs: "Nebulosa del Aguila",
    catalog: ["M16", "NGC 6611"],
    constellation: "Serpens",
    raHours: 18.314,
    decDeg: -13.79,
    objectType: "Nebulosa de emision",
    aliases: ["Pillars of Creation", "Pilares de la Creacion"],
    anchorStar: {
      id: "hd-168076",
      name: "HD 168076",
      constellation: "Serpens",
      raHours: 18.313,
      decDeg: -13.807,
      mag: 8.2,
      distanceLy: 5700,
      spectral: "O4V",
      bv: -0.2,
      searchAliases: ["NGC 6611"]
    }
  },
  {
    id: "omega-nebula",
    name: "Omega Nebula",
    nameEs: "Nebulosa Omega",
    catalog: ["M17", "NGC 6618"],
    constellation: "Sagittarius",
    raHours: 18.347,
    decDeg: -16.18,
    objectType: "Nebulosa de emision",
    aliases: ["Swan Nebula", "Nebulosa del Cisne"],
    anchorStar: {
      id: "hd-168607",
      name: "HD 168607",
      constellation: "Sagittarius",
      raHours: 18.348,
      decDeg: -16.376,
      mag: 8.3,
      distanceLy: 7200,
      spectral: "B9Ia",
      bv: 0.4,
      searchAliases: ["M17 field star"]
    }
  },
  {
    id: "north-america-nebula",
    name: "North America Nebula",
    nameEs: "Nebulosa Norteamerica",
    catalog: ["NGC 7000", "Caldwell 20"],
    constellation: "Cygnus",
    raHours: 20.974,
    decDeg: 44.333,
    objectType: "Nebulosa de emision",
    aliases: ["North America"],
    anchorStar: {
      id: "deneb",
      name: "Deneb",
      constellation: "Cygnus",
      raHours: 20.691,
      decDeg: 45.281,
      mag: 1.25,
      distanceLy: 2600,
      spectral: "A2Ia",
      bv: 0.09
    }
  },
  {
    id: "veil-nebula",
    name: "Veil Nebula",
    nameEs: "Nebulosa del Velo",
    catalog: ["NGC 6960", "Caldwell 34"],
    constellation: "Cygnus",
    raHours: 20.757,
    decDeg: 30.72,
    objectType: "Remanente de supernova",
    aliases: ["Western Veil", "Witch's Broom"],
    anchorStar: {
      id: "52-cygni",
      name: "52 Cygni",
      constellation: "Cygnus",
      raHours: 20.761,
      decDeg: 30.719,
      mag: 4.22,
      distanceLy: 291,
      spectral: "K0III",
      bv: 1.0,
      searchAliases: ["52 Cyg"]
    }
  },
  {
    id: "california-nebula",
    name: "California Nebula",
    nameEs: "Nebulosa California",
    catalog: ["NGC 1499"],
    constellation: "Perseus",
    raHours: 4.033,
    decDeg: 36.367,
    objectType: "Nebulosa de emision",
    aliases: ["California"],
    anchorStar: {
      id: "xi-persei",
      name: "Xi Persei",
      constellation: "Perseus",
      raHours: 3.983,
      decDeg: 35.791,
      mag: 4.04,
      distanceLy: 1200,
      spectral: "O7.5III",
      bv: 0.0,
      searchAliases: ["Menkib", "Xi Per"]
    }
  },
  {
    id: "flaming-star-nebula",
    name: "Flaming Star Nebula",
    nameEs: "Nebulosa Estrella Flameante",
    catalog: ["IC 405", "Sh2-229"],
    constellation: "Auriga",
    raHours: 5.275,
    decDeg: 34.312,
    objectType: "Nebulosa de emision/reflexion",
    aliases: ["Flaming Star"],
    anchorStar: {
      id: "ae-aurigae",
      name: "AE Aurigae",
      constellation: "Auriga",
      raHours: 5.276,
      decDeg: 34.312,
      mag: 5.99,
      distanceLy: 1500,
      spectral: "O9.5V",
      bv: -0.05,
      searchAliases: ["AE Aur"]
    }
  },
  {
    id: "crab-nebula",
    name: "Crab Nebula",
    nameEs: "Nebulosa del Cangrejo",
    catalog: ["M1", "NGC 1952"],
    constellation: "Taurus",
    raHours: 5.576,
    decDeg: 22.015,
    objectType: "Remanente de supernova",
    aliases: ["Crab"],
    anchorStar: {
      id: "crab-pulsar",
      name: "Crab Pulsar",
      constellation: "Taurus",
      raHours: 5.576,
      decDeg: 22.015,
      mag: 16.5,
      distanceLy: 6500,
      spectral: "B",
      bv: 0.0,
      searchAliases: ["PSR B0531+21", "CM Tauri"]
    }
  },
  {
    id: "helix-nebula",
    name: "Helix Nebula",
    nameEs: "Nebulosa Helice",
    catalog: ["NGC 7293", "Caldwell 63"],
    constellation: "Aquarius",
    raHours: 22.495,
    decDeg: -20.837,
    objectType: "Nebulosa planetaria",
    aliases: ["Helix"],
    anchorStar: {
      id: "helix-central-star",
      name: "Helix Central Star",
      constellation: "Aquarius",
      raHours: 22.495,
      decDeg: -20.837,
      mag: 13.5,
      distanceLy: 650,
      spectral: "DAO",
      bv: -0.3,
      searchAliases: ["WD 2226-210"]
    }
  }
];
